name: Build and push Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

# Enables BuildKit
env:
  DOCKER_BUILDKIT: 1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    # TODO: Change `repository` to the image's Docker repository name
    # TODO: Change `registry` to your private registry's domain
    - name: Build and push image
      uses: docker/build-push-action@v0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: myorg/myrepo
        registry: docker.pkg.github.com
        tag_with_ref: true
        add_git_labels: true
