name: test

on:
  push:
    branches:
      - master
      - v2-working-branch # remove when merged to master
  pull_request:
    branches:
      - master
      - v2-working-branch # remove when merged to master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Install
        run: yarn install
      -
        name: Test
        run: yarn run test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v1.0.13
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
